package it.grational.compare

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 21-03-2021 06.07
 */
@Slf4j
class ComparableArray {
	/**
	 * This method returns always true.
	 */
	Boolean someComparableArrayMethod() {
		true
	}
}
