package it.grational.compare

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author d7392
 * @date 21-03-2021 06.07
 */
class ComparableArraySpec extends Specification {
	def "someComparableArrayMethod returns true"() {
		setup:
			ComparableArray lib = new ComparableArray()
		when:
			Boolean result = lib.someComparableArrayMethod()
		then:
			result == true
	}
}
